name: Changelog

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4
        with:
          my_token: ${{ secrets.GITHUB }}

      - name: Create Release Pull Request or Release
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-pull-request@v6
        with:
          commit-message: "chore: update changelog"
          title: "Changelog Update"
          body: |
            Automated changelog update.
            
            ${{ steps.changelog.outputs.changelog }}
          branch: changelog-update
          delete-branch: true
